### ISSUE TITLE
Hardcoded URLs not declared as static

### ISSUE THREAD

**Issue by Adrisui3** [daviyisu/Lobby-Back#1]
Attributes for the GameCrontroller class holding the base URLs for data providers should be declared static as they are not defined per instance. Also, please consider using uppercase for static constants within a class. For instance: STEAM_API_BASE.

![image](https://github.com/daviyisu/Lobby-Back/assets/48246766/1d5fbb23-0174-4b87-b340-5fd633c4d83d)

**Comment by daviyisu** [comment]
Done, thanks
